FROM openjdk:17-alpine

ARG APP_NAME=target/*.jar
COPY ${APP_NAME} api.jar

ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ENV PORT=${PORT}
ENV PROFILE_ACTIVE=${PROFILE_ACTIVE}

ENTRYPOINT ["java","-Xmx512m","-Dserver.port=${PORT}", "-jar", "api.jar"]